/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package servidor;

import controle.ControleCliente;
import controle.ControleProduto;
import java.io.IOException;
import java.net.ServerSocket;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Marcos
 */
public class JFPrinicipalServidor extends javax.swing.JFrame {

    private DefaultListModel<String> listaA;

    private int numClientes;
    private ServerSocket s0;
    /**
     * Creates new form JFPrinicipalServidor
     */
    public JFPrinicipalServidor() {        
        preActions();
        initComponents();
        txtStatus.setText("OFFLINE");
        btmFechar.setEnabled(true);

    }

    private void preActions(){
        numClientes = 0;
        listaA = new DefaultListModel<String> ();    
        try {
            s0 = new ServerSocket(5050);
        } catch (IOException ex) {
            Logger.getLogger(JFPrinicipalServidor.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtVersaoApp = new javax.swing.JTextField();
        jlbServerName = new javax.swing.JLabel();
        jcomboEscolhaServidor = new javax.swing.JComboBox();
        jlbClientes = new javax.swing.JLabel();
        jscrolIpClientes = new javax.swing.JScrollPane();
        jlistIPClientes = new javax.swing.JList();
        btmIniciarServico = new javax.swing.JButton();
        btmPararServico = new javax.swing.JButton();
        btmFechar = new javax.swing.JButton();
        jlbTitulo = new javax.swing.JLabel();
        jlbStatus = new javax.swing.JLabel();
        jlnVersao = new javax.swing.JLabel();
        txtStatus = new javax.swing.JTextField();
        jlbNumClientes = new javax.swing.JLabel();
        txtNumClientes = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtVersaoApp.setText("v_1.0");

        jlbServerName.setText("Server Name: ");

        jcomboEscolhaServidor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "unesa", "Pander 1", "Pander 2", " " }));

        jlbClientes.setText("Clientes");

        jlistIPClientes.setModel(listaA  );
        jscrolIpClientes.setViewportView(jlistIPClientes);

        btmIniciarServico.setText("INICIAR SERVIDOR");
        btmIniciarServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmIniciarServicoActionPerformed(evt);
            }
        });

        btmPararServico.setText("PARAR SERVIDOR");
        btmPararServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmPararServicoActionPerformed(evt);
            }
        });

        btmFechar.setText("FECHAR");
        btmFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmFecharActionPerformed(evt);
            }
        });

        jlbTitulo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlbTitulo.setText("Pandera Studios Server");

        jlbStatus.setText("STATUS DO SERVIDOR:");

        jlnVersao.setText("Versão");

        jlbNumClientes.setText("NUM. CLIENTES:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlbTitulo)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jlbClientes)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jlbServerName)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jcomboEscolhaServidor, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jscrolIpClientes)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jlnVersao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtVersaoApp, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btmPararServico)
                            .addComponent(btmIniciarServico)
                            .addComponent(btmFechar))
                        .addGap(19, 19, 19))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlbStatus)
                            .addComponent(txtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlbNumClientes)
                            .addComponent(txtNumClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbTitulo)
                    .addComponent(jlnVersao)
                    .addComponent(txtVersaoApp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlbServerName)
                            .addComponent(jcomboEscolhaServidor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addComponent(jlbClientes)
                        .addGap(15, 15, 15)
                        .addComponent(jscrolIpClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btmIniciarServico)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btmPararServico)
                        .addGap(20, 20, 20)
                        .addComponent(jlbStatus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(jlbNumClientes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNumClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(btmFechar)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btmIniciarServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmIniciarServicoActionPerformed
        // TODO add your handling code here:

        txtStatus.setText("ONLINE");
        
        if (listaA == null)        
            preActions();

        try {
            System.out.println("Cheguei Aqui 2.1");
        
            try {
                ControleCliente.carregarDados();
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(JFPrinicipalServidor.class.getName()).log(Level.SEVERE, null, ex);
                }


                System.out.println("Cheguei Aqui 2.2");


            
            JOptionPane.showMessageDialog(null, "Servidor Correndo", "Servidor",
                JOptionPane.INFORMATION_MESSAGE);

            while (true)
            {
                numClientes++;
                listaA.insertElementAt(numClientes + " - IP: " + s0.getInetAddress(),0);
                txtNumClientes.setText("" + numClientes);
                
                new ThCliente(s0.accept()).start();

                JOptionPane.showMessageDialog(null,
                    "Cliente:" + s0.getInetAddress() + "Esta Conectado a Porta: " + s0.getLocalPort(),
                    "Cliente Conectado", JOptionPane.INFORMATION_MESSAGE);
//                JOptionPane.getFrameForComponent(this).repaint();

                System.out.println("ip>" + s0.getInetAddress());
                                
            }
        } catch (IOException ex) {
            Logger.getLogger(JFPrinicipalServidor.class.getName()).log(Level.SEVERE, null, ex);
        }

        btmIniciarServico.setEnabled(false);
        btmPararServico.setEnabled(true);
        btmFechar.setEnabled(true);
    }//GEN-LAST:event_btmIniciarServicoActionPerformed

    private void btmFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmFecharActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            s0.close();
            
        } catch (IOException ex) {
            Logger.getLogger(JFPrinicipalServidor.class.getName()).log(Level.SEVERE, null, ex);
        }finally{
            txtStatus.setText("OFFLINE");
        }
        listaA.clear();
        System.exit(0);
    }//GEN-LAST:event_btmFecharActionPerformed

    private void btmPararServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmPararServicoActionPerformed
        try {
            // TODO add your handling code here:
            s0.close();
        } catch (IOException ex) {
            Logger.getLogger(JFPrinicipalServidor.class.getName()).log(Level.SEVERE, null, ex);
        }
        listaA.clear();
        btmIniciarServico.setEnabled(true);
    }//GEN-LAST:event_btmPararServicoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFPrinicipalServidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFPrinicipalServidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFPrinicipalServidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFPrinicipalServidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFPrinicipalServidor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btmFechar;
    private javax.swing.JButton btmIniciarServico;
    private javax.swing.JButton btmPararServico;
    private javax.swing.JComboBox jcomboEscolhaServidor;
    private javax.swing.JLabel jlbClientes;
    private javax.swing.JLabel jlbNumClientes;
    private javax.swing.JLabel jlbServerName;
    private javax.swing.JLabel jlbStatus;
    private javax.swing.JLabel jlbTitulo;
    private javax.swing.JList jlistIPClientes;
    private javax.swing.JLabel jlnVersao;
    private javax.swing.JScrollPane jscrolIpClientes;
    private javax.swing.JTextField txtNumClientes;
    private javax.swing.JTextField txtStatus;
    private javax.swing.JTextField txtVersaoApp;
    // End of variables declaration//GEN-END:variables
}
